spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: quseis@gmail.com
    password: zfilqhajdjgtzmlh
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://portfolio.cnnw9ccj3lgu.ap-northeast-2.rds.amazonaws.com:3306/health_management
    username: admin
    password: 1q2w3e4r
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 590152913048-735d95gorit803gvqs2n69jfj3vsnjn3.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-id: 9645a81ef824d5e2655b2f8c0a4c27b0
            client-secret: k08oyR8BAJRVZvb2NerVxI3ZxvfICLQh
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id: zhR2CCT8kjFeje8j3B3P
            client-secret: jZ6Ev4VATy
            redirect-uri:  http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
    
mybatis:
  mapper-locations:
    - /mappers/*.xml
    
jwt:
  secret: n9GeQdOVaqlkAH3kMmKcCSpp2KDvk697oUXqFRXjCiFPCoou5UgrxV9vX70vTekO
  
file:
  path: C:\aws_project\workspace\healthmanagement\healthmanagement_back\upLoad\